### PR TITLE
Add py.typed marker file named to support type checking

### PR DESCRIPTION
**Pull request by kirill-gr**
Fixes https://github.com/cloud-custodian/cel-python/issues/39

### CODE REVIEW

**Comment by kirill-gr** [comment]
@kapilt would you mind taking a look?

**Comment by kapilt** [comment]
an empty file resolves the error?

**Comment by kirill-gr** [comment]
Yes, see: https://peps.python.org/pep-0561/#packaging-type-information

> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing.

**Comment by inikolaev** [comment]
Where are examples from other popular libraries that make use of `py.typed`:

- [httpx](https://github.com/encode/httpx/blob/master/httpx/py.typed) an async HTTP client
- [dd-trace-py](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/py.typed) a DataDog tracing library

**Comment by kapilt** [comment]
Totally understand the value, but the pr at the moment adds an empty file,
which seems somewhat superfluous to the goal

**Comment by inikolaev** [comment]
Apparently that is how it needs to be done to enable type checker to understand that the package supports types as per spec and as you can see from example projects.

Do you see that anything else needs to be done as part of of this PR? I had an impression the package already uses type annotations it just that they are not being used by `mypy` because of the missing marker file.

How do you propose to solve this?

**Review by kapilt — APPROVED** [review]
lgtm

**Comment by kapilt** [comment]
thanks for the additional context re other project links

**Pull request merged**
