### PR TITLE
Update badges in README

### PR DESCRIPTION
**Pull request by simonw**
The requires.io one no longer works, and it looks like CI has moved from Travis to GitHub Actions.

### CODE REVIEW

**Comment by simonw** [comment]
I tried signing the CLA but got this error:
```json
{
  "errors": {
    "github_oauth2_token": "Token permissions have been rejected, please try again"
  }
}
```

**Comment by kapilt** [comment]
hi @simonw I pinged the "easycla" people in the cncf slack, I haven't seen the error you referenced before :/

**Comment by kapilt** [comment]
Cla issue seems resolved, thanks. The lint ci issue seems to be on trunk, I’m currently revamping ci/publishing (trustless pypi annd slsa)  across the repos in this org, will address this one in next week. Thanks for the contribution.

**Review by kapilt — APPROVED** [review]
thanks, lgtm

**Pull request merged**
